const PDFDocument = require('pdfkit');

/**
 * Generates a simple invoice PDF into the given writable stream.
 * 'invoice' is a populated Invoice document (with saleId + sellerId)
 */

function generateInvoicePdf(invoice, stream) {
    const doc = new PDFDocument({ margin: 50 });

    //pipe PDF to the stream (express response or file)
    doc.pipe(stream);

    //========== HEADER ==========
    doc
    .fontSize(20)
    .text('I.S.T.D PRO - Invoice', { align: 'left' })
    .moveDown();

    doc
    .fontSize(12)
    .text(`Invoice #: ${invoice.invoiceNumber}`)
    .text(`Status: ${invoice.status}`)
    .text(`Invoice Date: ${invoice.invoiceDate.toDateString()}`)
    .text(`Due Date: ${invoice.dueDate.toDateString()}`)
    .modeDown();

    //========== CUSTOMER INFO ==========
    doc
    .fontSize(12)
    .text('Bill To:', { underline: true })
    .moveDown();

    doc
    .fontSize(12)
    .text(invoice.customerName)
    .text(invoice.customerEmail)
    .text(invoice.customerPhone || '')
    .moveDown();

    // ========== ITEMS TABLE ==========
    doc.fontSize(14).text('Items', { underline: true }).moveDown(0.3);
  
    // Table headers
    doc
      .fontSize(12)
      .text('Product', 50, doc.y, { continued: true })
      .text('Qty', 250, doc.y, { continued: true })
      .text('Unit Price', 300, doc.y, { continued: true })
      .text('Total', 400, doc.y);
  
    doc.moveDown(0.5);
  
    // Draw a line under headers
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.5);
  
    // Items
    invoice.items.forEach((item) => {
      doc
        .fontSize(12)
        .text(item.productName, 50, doc.y, { continued: true })
        .text(item.quantity.toString(), 250, doc.y, { continued: true })
        .text(item.unitPrice.toFixed(2), 300, doc.y, { continued: true })
        .text(item.itemTotal.toFixed(2), 400, doc.y);
    });
  
    doc.moveDown();
  
    // ========== TOTALS ==========
    doc.moveDown();
    doc
      .fontSize(12)
      .text(`Subtotal: $${invoice.subtotal.toFixed(2)}`, { align: 'right' })
      .text(`Tax (${invoice.taxPercentage}%): $${invoice.taxAmount.toFixed(2)}`, {
        align: 'right',
      })
      .text(`Total: $${invoice.totalAmount.toFixed(2)}`, { align: 'right' })
      .moveDown();
  
    // ========== NOTES ==========
    if (invoice.notes) {
      doc
        .moveDown()
        .fontSize(12)
        .text('Notes:', { underline: true })
        .moveDown(0.3)
        .text(invoice.notes);
    }
  
    // ========== FOOTER ==========
    doc.moveDown(2);
    doc
      .fontSize(10)
      .fillColor('gray')
      .text('Generated by I.S.T.D PRO', { align: 'center' });
  
    doc.end();
  }
  
  module.exports = { generateInvoicePdf };