const PDFDocument = require('pdfkit');

// ─── Design Tokens ────────────────────────────────────────────────────────────
const COLORS = {
  primary:   '#1a3c5e',
  accent:    '#2e86c1',
  light:     '#eaf4fb',
  border:    '#b0cfe8',
  textDark:  '#1c2833',
  textMid:   '#566573',
  textLight: '#aab7c4',
  white:     '#ffffff',
  rowAlt:    '#f4f9fd',
};

const MARGIN    = 50;
const PAGE_W    = 595.28;  // A4 width in pt
const PAGE_H    = 841.89;  // A4 height in pt
const CONTENT_W = PAGE_W - MARGIN * 2;

// ─── Layout boundaries ────────────────────────────────────────────────────────
const BANNER_H    = 80;
const FOOTER_H    = 32;
const BODY_TOP    = BANNER_H + 4;
const BODY_BOTTOM = PAGE_H - FOOTER_H - 8; // content must never exceed this Y

// Table column definitions
const COL = {
  product:   { x: MARGIN,       w: 180 },
  qty:       { x: MARGIN + 185, w:  55 },
  unitPrice: { x: MARGIN + 245, w:  90 },
  total:     { x: MARGIN + 340, w:  95 },
};

// ─── Drawing helpers ──────────────────────────────────────────────────────────

function fillRect(doc, x, y, w, h, color) {
  doc.save().rect(x, y, w, h).fill(color).restore();
}

function hRule(doc, y, color = COLORS.border, x = MARGIN, w = CONTENT_W) {
  doc.save().moveTo(x, y).lineTo(x + w, y).lineWidth(0.5).strokeColor(color).stroke().restore();
}

function fmtDate(d) {
  if (!d) return '—';
  const date = d instanceof Date ? d : new Date(d);
  return date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

// ─── Sticky header & footer (painted on every page) ──────────────────────────

function drawPageHeader(doc, invoice) {
  fillRect(doc, 0, 0, PAGE_W, BANNER_H, COLORS.primary);

  doc
    .font('Helvetica-Bold').fontSize(22).fillColor(COLORS.white)
    .text('I.S.T.D PRO', MARGIN, 22, { continued: true })
    .font('Helvetica').fontSize(14).fillColor('#a9cce3')
    .text('  ·  Invoice', { continued: false });

  doc
    .font('Helvetica').fontSize(9).fillColor('#a9cce3')
    .text('Powered by I.S.T.D PRO Platform', MARGIN, 48);

  doc
    .font('Helvetica-Bold').fontSize(11).fillColor(COLORS.white)
    .text(`#${invoice.invoiceNumber}`, PAGE_W - MARGIN - 130, 22, { width: 130, align: 'right' });

  const statusColor = invoice.status === 'Paid' ? '#27ae60' : '#e67e22';
  doc.roundedRect(PAGE_W - MARGIN - 75, 40, 75, 20, 4).fill(statusColor);
  doc
    .font('Helvetica-Bold').fontSize(9).fillColor(COLORS.white)
    .text(invoice.status.toUpperCase(), PAGE_W - MARGIN - 75, 46, { width: 75, align: 'center' });
}

function drawPageFooter(doc, pageNumber) {
  const fy = PAGE_H - FOOTER_H;
  hRule(doc, fy, COLORS.border);
  doc
    .font('Helvetica').fontSize(8).fillColor(COLORS.textLight)
    .text(
      `Generated by I.S.T.D PRO  ·  ${new Date().toLocaleDateString('en-US', {
        year: 'numeric', month: 'long', day: 'numeric',
      })}`,
      MARGIN, fy + 10,
      { width: CONTENT_W / 2, align: 'left' }
    )
    .text(
      `Page ${pageNumber}`,
      MARGIN, fy + 10,
      { width: CONTENT_W, align: 'right' }
    );
}

// ─── Table header row (re-drawn when a page break splits the item list) ───────

const TH_H = 24;

function drawTableHeader(doc, y) {
  fillRect(doc, MARGIN, y, CONTENT_W, TH_H, COLORS.primary);
  doc.font('Helvetica-Bold').fontSize(9).fillColor(COLORS.white);
  doc.text('PRODUCT / DESCRIPTION', COL.product.x + 6,   y + 8, { width: COL.product.w,   lineBreak: false });
  doc.text('QTY',                   COL.qty.x,            y + 8, { width: COL.qty.w,       align: 'center', lineBreak: false });
  doc.text('UNIT PRICE',            COL.unitPrice.x,      y + 8, { width: COL.unitPrice.w, align: 'right',  lineBreak: false });
  doc.text('TOTAL',                 COL.total.x,          y + 8, { width: COL.total.w,     align: 'right',  lineBreak: false });
  return y + TH_H;
}

// ─── Main generator ───────────────────────────────────────────────────────────

/**
 * Generates a polished invoice PDF into the given writable stream.
 *
 * The header banner and footer are "sticky" — they are painted on every page,
 * including any overflow pages created when the item list is long.
 * Content is constrained to BODY_TOP … BODY_BOTTOM so it never overlaps them.
 *
 * @param {object} invoice  Populated invoice document
 * @param {Stream} stream   Writable stream (Express res or fs.createWriteStream)
 */
function generateInvoicePdf(invoice, stream) {
  const doc = new PDFDocument({
    margin: 0,       // we handle all positioning manually
    size: 'A4',
    autoFirstPage: false,
  });

  doc.pipe(stream);

  // ── Page helpers ──────────────────────────────────────────────────────────

  let pageNumber = 0;

  /** Add a page and stamp header + footer immediately */
  function addPage() {
    pageNumber++;
    doc.addPage();
    drawPageHeader(doc, invoice);
    drawPageFooter(doc, pageNumber);
  }

  /**
   * If `neededHeight` no longer fits between curY and BODY_BOTTOM,
   * add a new page and return the fresh starting Y (BODY_TOP + padding).
   * Otherwise return curY unchanged.
   */
  function ensureSpace(curY, neededHeight) {
    if (curY + neededHeight > BODY_BOTTOM) {
      addPage();
      return BODY_TOP + 10;
    }
    return curY;
  }

  // ── Page 1 ────────────────────────────────────────────────────────────────
  addPage();

  // ── Meta strip (invoice date / due date) ──────────────────────────────────
  const META_Y = BANNER_H + 18;
  fillRect(doc, MARGIN, META_Y, CONTENT_W, 52, COLORS.light);
  doc.save().rect(MARGIN, META_Y, CONTENT_W, 52).lineWidth(0.5).strokeColor(COLORS.border).stroke().restore();

  const dc1 = MARGIN + 14;
  const dc2 = MARGIN + CONTENT_W / 2 + 10;
  doc.font('Helvetica-Bold').fontSize(8).fillColor(COLORS.textMid)
     .text('INVOICE DATE', dc1, META_Y + 10)
     .text('DUE DATE',     dc2, META_Y + 10);
  doc.font('Helvetica').fontSize(10).fillColor(COLORS.textDark)
     .text(fmtDate(invoice.invoiceDate), dc1, META_Y + 23)
     .text(fmtDate(invoice.dueDate),     dc2, META_Y + 23);

  // ── Bill To ───────────────────────────────────────────────────────────────
  let curY = META_Y + 72;

  doc.font('Helvetica-Bold').fontSize(9).fillColor(COLORS.accent).text('BILL TO', MARGIN, curY);
  hRule(doc, curY + 13, COLORS.accent, MARGIN, 80);
  curY += 20;

  doc.font('Helvetica-Bold').fontSize(11).fillColor(COLORS.textDark).text(invoice.customerName, MARGIN, curY);
  curY += 15;
  doc.font('Helvetica').fontSize(10).fillColor(COLORS.textMid).text(invoice.customerEmail, MARGIN, curY);
  curY += 13;
  if (invoice.customerPhone) {
    doc.text(invoice.customerPhone, MARGIN, curY);
    curY += 13;
  }

  // ── Line Items ────────────────────────────────────────────────────────────
  curY += 20;
  curY = ensureSpace(curY, 60);

  doc.font('Helvetica-Bold').fontSize(9).fillColor(COLORS.accent).text('LINE ITEMS', MARGIN, curY);
  hRule(doc, curY + 13, COLORS.accent, MARGIN, 110);
  curY += 22;

  // Draw the initial table header
  curY = ensureSpace(curY, TH_H + 22);
  curY = drawTableHeader(doc, curY);

  // Track the top of the current table segment for the outer border
  let tableSegmentTopY = curY - TH_H;
  let prevPageNum      = pageNumber;

  invoice.items.forEach((item, idx) => {
    const ROW_H = 22;
    const beforeY    = curY;
    const beforePage = pageNumber;

    curY = ensureSpace(curY, ROW_H);

    // Page break happened — close the previous table segment's border,
    // then re-draw the column headers on the new page.
    if (pageNumber !== beforePage) {
      doc.save()
         .rect(MARGIN, tableSegmentTopY, CONTENT_W, beforeY - tableSegmentTopY)
         .lineWidth(0.5).strokeColor(COLORS.border).stroke()
         .restore();

      curY = drawTableHeader(doc, curY);
      tableSegmentTopY = curY - TH_H;
    }

    const rowBg = idx % 2 === 0 ? COLORS.white : COLORS.rowAlt;
    fillRect(doc, MARGIN, curY, CONTENT_W, ROW_H, rowBg);

    doc.font('Helvetica').fontSize(10).fillColor(COLORS.textDark);
    doc.text(item.productName,                COL.product.x + 6,  curY + 6, { width: COL.product.w,   lineBreak: false });
    doc.text(String(item.quantity),           COL.qty.x,           curY + 6, { width: COL.qty.w,       align: 'center', lineBreak: false });
    doc.text(`$${item.unitPrice.toFixed(2)}`, COL.unitPrice.x,     curY + 6, { width: COL.unitPrice.w, align: 'right',  lineBreak: false });
    doc.text(`$${item.itemTotal.toFixed(2)}`, COL.total.x,         curY + 6, { width: COL.total.w,     align: 'right',  lineBreak: false });

    hRule(doc, curY + ROW_H, COLORS.border);
    curY += ROW_H;
  });

  // Close the final table segment border
  doc.save()
     .rect(MARGIN, tableSegmentTopY, CONTENT_W, curY - tableSegmentTopY)
     .lineWidth(0.5).strokeColor(COLORS.border).stroke()
     .restore();

  // ── Totals block ──────────────────────────────────────────────────────────
  const TOTALS_H = 80;
  curY += 20;
  curY = ensureSpace(curY, TOTALS_H);

  const TOTALS_W = 220;
  const TOTALS_X = MARGIN + CONTENT_W - TOTALS_W;
  const labelX   = TOTALS_X + 12;

  fillRect(doc, TOTALS_X, curY, TOTALS_W, TOTALS_H, COLORS.light);
  doc.save().rect(TOTALS_X, curY, TOTALS_W, TOTALS_H).lineWidth(0.5).strokeColor(COLORS.border).stroke().restore();

  function totalRow(label, value, y, bold = false, big = false) {
    const font  = bold ? 'Helvetica-Bold' : 'Helvetica';
    const size  = big  ? 13 : 10;
    const color = big  ? COLORS.primary : COLORS.textDark;
    doc.font(font).fontSize(size).fillColor(COLORS.textMid).text(label, labelX, y);
    doc.font(font).fontSize(size).fillColor(color).text(value, labelX, y, { width: TOTALS_W - 24, align: 'right' });
  }

  totalRow('Subtotal',                        `$${invoice.subtotal.toFixed(2)}`,    curY + 12);
  totalRow(`Tax (${invoice.taxPercentage}%)`, `$${invoice.taxAmount.toFixed(2)}`,   curY + 30);
  hRule(doc, curY + 52, COLORS.border, TOTALS_X + 12, TOTALS_W - 24);
  totalRow('Total Due',                       `$${invoice.totalAmount.toFixed(2)}`, curY + 58, true, true);

  curY += TOTALS_H + 20;

  // ── Notes ─────────────────────────────────────────────────────────────────
  if (invoice.notes) {
    const notesTextH = doc.heightOfString(invoice.notes, { width: CONTENT_W - 20 });
    const notesBlockH = notesTextH + 50;
    curY = ensureSpace(curY, notesBlockH);

    doc.font('Helvetica-Bold').fontSize(9).fillColor(COLORS.accent).text('NOTES', MARGIN, curY);
    hRule(doc, curY + 13, COLORS.accent, MARGIN, 60);
    curY += 22;

    fillRect(doc, MARGIN, curY, CONTENT_W, notesTextH + 16, COLORS.rowAlt);
    doc.save().rect(MARGIN, curY, CONTENT_W, notesTextH + 16).lineWidth(0.5).strokeColor(COLORS.border).stroke().restore();
    doc.font('Helvetica').fontSize(10).fillColor(COLORS.textMid)
       .text(invoice.notes, MARGIN + 10, curY + 8, { width: CONTENT_W - 20 });
  }

  doc.end();
}

module.exports = { generateInvoicePdf };