const PDFDocument = require('pdfkit');

// ─── Design Tokens — matches dashboard brand palette ─────────────────────────
const COLORS = {
  navyDark:   '#0f1b3d',   // sidebar dark end
  navyMid:    '#1a2f6b',   // sidebar top / header bg
  blue:       '#3B5CD4',   // primary brand blue
  cyan:       '#3A96D4',   // accent cyan
  green:      '#33B833',   // paid / success
  orange:     '#f59e0b',   // pending
  red:        '#ef4444',   // overdue / cancelled
  slate50:    '#f8fafc',   // card background
  slate100:   '#f1f5f9',   // alternate row
  slate200:   '#e2e8f0',   // borders
  slate400:   '#94a3b8',   // muted text
  slate600:   '#475569',   // secondary text
  slate800:   '#1e293b',   // primary text
  white:      '#ffffff',
};

const MARGIN    = 50;
const PAGE_W    = 595.28;
const PAGE_H    = 841.89;
const CONTENT_W = PAGE_W - MARGIN * 2;

// ─── Layout boundaries ────────────────────────────────────────────────────────
const BANNER_H    = 72;
const FOOTER_H    = 30;
const BODY_TOP    = BANNER_H + 4;
const BODY_BOTTOM = PAGE_H - FOOTER_H - 8;

// Table column definitions
const COL = {
  product:   { x: MARGIN,       w: 190 },
  qty:       { x: MARGIN + 195, w:  50 },
  unitPrice: { x: MARGIN + 250, w:  95 },
  total:     { x: MARGIN + 350, w:  95 },
};

// ─── Drawing helpers ──────────────────────────────────────────────────────────

function fillRect(doc, x, y, w, h, color) {
  doc.save().rect(x, y, w, h).fill(color).restore();
}

function hRule(doc, y, color = COLORS.slate200, x = MARGIN, w = CONTENT_W) {
  doc.save().moveTo(x, y).lineTo(x + w, y).lineWidth(0.5).strokeColor(color).stroke().restore();
}

function fmtDate(d) {
  if (!d) return '—';
  const date = d instanceof Date ? d : new Date(d);
  return date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

// ─── Status badge color ───────────────────────────────────────────────────────
function statusColor(status) {
  switch ((status || '').toLowerCase()) {
    case 'paid':      return COLORS.green;
    case 'pending':   return COLORS.orange;
    case 'overdue':   return COLORS.red;
    case 'cancelled': return COLORS.red;
    case 'sent':      return COLORS.blue;
    default:          return COLORS.slate400; // draft
  }
}

// ─── Sticky header ────────────────────────────────────────────────────────────
function drawPageHeader(doc, invoice) {
  // Navy background
  fillRect(doc, 0, 0, PAGE_W, BANNER_H, COLORS.navyMid);

  // Bottom accent stripe
  fillRect(doc, 0, BANNER_H - 3, PAGE_W, 3, COLORS.blue);

  // Brand icon square
  const iconX = MARGIN;
  const iconY = 16;
  doc.save().roundedRect(iconX, iconY, 32, 32, 6).fill(COLORS.blue).restore();
  doc.font('Helvetica-Bold').fontSize(16).fillColor(COLORS.white)
     .text('i', iconX + 11, iconY + 7, { lineBreak: false });

  // Brand name + subtitle
  doc.font('Helvetica-Bold').fontSize(14).fillColor(COLORS.white)
     .text('I.S.T.D PRO', iconX + 42, iconY + 4, { lineBreak: false });
  doc.font('Helvetica').fontSize(8).fillColor('#7ea8d4')
     .text('Management Platform', iconX + 42, iconY + 21, { lineBreak: false });

  // Invoice number (right side)
  doc.font('Helvetica-Bold').fontSize(11).fillColor(COLORS.white)
     .text(`Invoice #${invoice.invoiceNumber}`, PAGE_W - MARGIN - 160, iconY + 2, {
       width: 160, align: 'right', lineBreak: false,
     });

  // Status pill
  const sc     = statusColor(invoice.status);
  const badgeW = 74;
  const badgeX = PAGE_W - MARGIN - badgeW;
  const badgeY = iconY + 19;
  doc.save().roundedRect(badgeX, badgeY, badgeW, 15, 7).fill(sc).restore();
  doc.font('Helvetica-Bold').fontSize(7.5).fillColor(COLORS.white)
     .text((invoice.status || 'Draft').toUpperCase(), badgeX, badgeY + 4, {
       width: badgeW, align: 'center', lineBreak: false,
     });
}

// ─── Sticky footer ────────────────────────────────────────────────────────────
function drawPageFooter(doc, pageNumber) {
  const fy = PAGE_H - FOOTER_H;
  hRule(doc, fy, COLORS.slate200);
  doc.font('Helvetica').fontSize(7.5).fillColor(COLORS.slate400)
     .text(
       `Generated by I.S.T.D PRO  ·  ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
       MARGIN, fy + 10,
       { width: CONTENT_W / 2, align: 'left', lineBreak: false }
     )
     .text(
       `Page ${pageNumber}`,
       MARGIN, fy + 10,
       { width: CONTENT_W, align: 'right', lineBreak: false }
     );
}

// ─── Section label ────────────────────────────────────────────────────────────
function drawSectionLabel(doc, label, x, y) {
  doc.font('Helvetica-Bold').fontSize(7.5).fillColor(COLORS.blue)
     .text(label.toUpperCase(), x, y, { characterSpacing: 1, lineBreak: false });
  const tw = doc.widthOfString(label.toUpperCase(), { characterSpacing: 1 });
  doc.save()
     .moveTo(x, y + 11).lineTo(x + tw + 24, y + 11)
     .lineWidth(1).strokeColor(COLORS.blue).stroke()
     .restore();
}

// ─── Table header row ─────────────────────────────────────────────────────────
const TH_H = 26;

function drawTableHeader(doc, y) {
  fillRect(doc, MARGIN, y, CONTENT_W, TH_H, COLORS.navyMid);
  fillRect(doc, MARGIN, y, 3, TH_H, COLORS.cyan); // left accent stripe

  doc.font('Helvetica-Bold').fontSize(8).fillColor(COLORS.white);
  doc.text('PRODUCT / DESCRIPTION', COL.product.x + 10,  y + 9, { width: COL.product.w,   lineBreak: false });
  doc.text('QTY',                   COL.qty.x,            y + 9, { width: COL.qty.w,       align: 'center', lineBreak: false });
  doc.text('UNIT PRICE',            COL.unitPrice.x,      y + 9, { width: COL.unitPrice.w, align: 'right',  lineBreak: false });
  doc.text('TOTAL',                 COL.total.x,          y + 9, { width: COL.total.w,     align: 'right',  lineBreak: false });
  return y + TH_H;
}

// ─── Main generator ───────────────────────────────────────────────────────────
function generateInvoicePdf(invoice, stream) {
  const doc = new PDFDocument({ margin: 0, size: 'A4', autoFirstPage: false });
  doc.pipe(stream);

  let pageNumber = 0;

  function addPage() {
    pageNumber++;
    doc.addPage();
    drawPageHeader(doc, invoice);
    drawPageFooter(doc, pageNumber);
  }

  function ensureSpace(curY, neededHeight) {
    if (curY + neededHeight > BODY_BOTTOM) {
      addPage();
      return BODY_TOP + 10;
    }
    return curY;
  }

  // ── Page 1 ────────────────────────────────────────────────────────────────
  addPage();

  // ── Meta strip — dates card ───────────────────────────────────────────────
  const META_Y = BANNER_H + 16;
  fillRect(doc, MARGIN, META_Y, CONTENT_W, 50, COLORS.slate50);
  doc.save().rect(MARGIN, META_Y, CONTENT_W, 50)
     .lineWidth(0.5).strokeColor(COLORS.slate200).stroke().restore();
  fillRect(doc, MARGIN, META_Y, 3, 50, COLORS.blue); // left accent

  const col1 = MARGIN + 16;
  const col2 = MARGIN + CONTENT_W / 2 + 10;

  doc.font('Helvetica-Bold').fontSize(7.5).fillColor(COLORS.slate400)
     .text('INVOICE DATE', col1, META_Y + 10, { lineBreak: false })
     .text('DUE DATE',     col2, META_Y + 10, { lineBreak: false });

  doc.font('Helvetica-Bold').fontSize(11).fillColor(COLORS.slate800)
     .text(fmtDate(invoice.invoiceDate), col1, META_Y + 25, { lineBreak: false })
     .text(fmtDate(invoice.dueDate),     col2, META_Y + 25, { lineBreak: false });

  // ── Bill To card ──────────────────────────────────────────────────────────
  let curY = META_Y + 70;
  drawSectionLabel(doc, 'Bill To', MARGIN, curY);
  curY += 20;

  const custH = invoice.customerPhone ? 64 : 50;
  fillRect(doc, MARGIN, curY, CONTENT_W, custH, COLORS.slate50);
  doc.save().rect(MARGIN, curY, CONTENT_W, custH)
     .lineWidth(0.5).strokeColor(COLORS.slate200).stroke().restore();
  fillRect(doc, MARGIN, curY, 3, custH, COLORS.cyan);

  doc.font('Helvetica-Bold').fontSize(12).fillColor(COLORS.slate800)
     .text(invoice.customerName, MARGIN + 16, curY + 10, { lineBreak: false });
  doc.font('Helvetica').fontSize(9.5).fillColor(COLORS.slate600)
     .text(invoice.customerEmail, MARGIN + 16, curY + 27, { lineBreak: false });
  if (invoice.customerPhone) {
    doc.font('Helvetica').fontSize(9).fillColor(COLORS.slate400)
       .text(invoice.customerPhone, MARGIN + 16, curY + 43, { lineBreak: false });
  }

  curY += custH + 26;

  // ── Line Items ────────────────────────────────────────────────────────────
  curY = ensureSpace(curY, 60);
  drawSectionLabel(doc, 'Line Items', MARGIN, curY);
  curY += 20;

  curY = ensureSpace(curY, TH_H + 24);
  curY = drawTableHeader(doc, curY);

  let tableSegmentTopY = curY - TH_H;

  invoice.items.forEach((item, idx) => {
    const ROW_H    = 24;
    const beforeY  = curY;
    const beforePg = pageNumber;

    curY = ensureSpace(curY, ROW_H);

    if (pageNumber !== beforePg) {
      doc.save()
         .rect(MARGIN, tableSegmentTopY, CONTENT_W, beforeY - tableSegmentTopY)
         .lineWidth(0.5).strokeColor(COLORS.slate200).stroke().restore();
      curY = drawTableHeader(doc, curY);
      tableSegmentTopY = curY - TH_H;
    }

    const rowBg = idx % 2 === 0 ? COLORS.white : COLORS.slate100;
    fillRect(doc, MARGIN, curY, CONTENT_W, ROW_H, rowBg);
    if (idx % 2 === 0) fillRect(doc, MARGIN, curY, 3, ROW_H, COLORS.slate200);

    doc.font('Helvetica').fontSize(9.5).fillColor(COLORS.slate800)
       .text(item.productName, COL.product.x + 10, curY + 7, { width: COL.product.w, lineBreak: false });

    doc.font('Helvetica').fontSize(9.5).fillColor(COLORS.slate600)
       .text(String(item.quantity),           COL.qty.x,       curY + 7, { width: COL.qty.w,       align: 'center', lineBreak: false })
       .text(`$${item.unitPrice.toFixed(2)}`, COL.unitPrice.x, curY + 7, { width: COL.unitPrice.w, align: 'right',  lineBreak: false });

    doc.font('Helvetica-Bold').fontSize(9.5).fillColor(COLORS.slate800)
       .text(`$${item.itemTotal.toFixed(2)}`, COL.total.x, curY + 7, { width: COL.total.w, align: 'right', lineBreak: false });

    hRule(doc, curY + ROW_H, COLORS.slate200);
    curY += ROW_H;
  });

  // Close final table border
  doc.save()
     .rect(MARGIN, tableSegmentTopY, CONTENT_W, curY - tableSegmentTopY)
     .lineWidth(0.5).strokeColor(COLORS.slate200).stroke().restore();

  // ── Totals card ───────────────────────────────────────────────────────────
  const TOTALS_H = 90;
  curY += 20;
  curY = ensureSpace(curY, TOTALS_H);

  const TOTALS_W = 230;
  const TOTALS_X = MARGIN + CONTENT_W - TOTALS_W;
  const labelX   = TOTALS_X + 14;

  fillRect(doc, TOTALS_X, curY, TOTALS_W, TOTALS_H, COLORS.slate50);
  doc.save().rect(TOTALS_X, curY, TOTALS_W, TOTALS_H)
     .lineWidth(0.5).strokeColor(COLORS.slate200).stroke().restore();
  fillRect(doc, TOTALS_X, curY, TOTALS_W, 3, COLORS.blue); // top accent

  function totalRow(label, value, y, highlight = false) {
    doc.font('Helvetica').fontSize(9.5).fillColor(COLORS.slate600)
       .text(label, labelX, y, { lineBreak: false });
    doc.font(highlight ? 'Helvetica-Bold' : 'Helvetica')
       .fontSize(highlight ? 12 : 9.5)
       .fillColor(highlight ? COLORS.blue : COLORS.slate800)
       .text(value, labelX, y, { width: TOTALS_W - 28, align: 'right', lineBreak: false });
  }

  totalRow('Subtotal',                        `$${invoice.subtotal.toFixed(2)}`,    curY + 14);
  totalRow(`Tax (${invoice.taxPercentage}%)`, `$${invoice.taxAmount.toFixed(2)}`,   curY + 33);
  hRule(doc, curY + 56, COLORS.slate200, labelX, TOTALS_W - 28);
  totalRow('Total Due',                       `$${invoice.totalAmount.toFixed(2)}`, curY + 64, true);

  curY += TOTALS_H + 24;

  // ── Notes card ────────────────────────────────────────────────────────────
  if (invoice.notes) {
    const notesTextH  = doc.heightOfString(invoice.notes, { width: CONTENT_W - 28 });
    const notesBlockH = notesTextH + 52;
    curY = ensureSpace(curY, notesBlockH);

    drawSectionLabel(doc, 'Notes', MARGIN, curY);
    curY += 20;

    const noteCardH = notesTextH + 20;
    fillRect(doc, MARGIN, curY, CONTENT_W, noteCardH, COLORS.slate50);
    doc.save().rect(MARGIN, curY, CONTENT_W, noteCardH)
       .lineWidth(0.5).strokeColor(COLORS.slate200).stroke().restore();
    fillRect(doc, MARGIN, curY, 3, noteCardH, COLORS.cyan);

    doc.font('Helvetica').fontSize(9.5).fillColor(COLORS.slate600)
       .text(invoice.notes, MARGIN + 16, curY + 10, { width: CONTENT_W - 28 });
  }

  doc.end();
}

module.exports = { generateInvoicePdf };