const mongoose = require('mongoose');

/**
 * PRODUCT SCHEMA
 * 
 * This defines the structure of a Product document in MongoDB
 * Products are the inventory items that ISTDPRO manages
 * 
 * Each product has:
 * - Identification: SKU (unique code), name
 * - Pricing: price (selling price), cost (purchase price)
 * - Inventory: stock (current quantity), minStock (reorder level)
 * - Details: description, category, supplier
 * - AI: aiGenerated flag (for features added on Day 7-8)
 */

const productSchema = new mongoose.Schema({
    /**
     * SKU FIELD
     * 
     * WHAT: Stock Keeping Unit - unique product identifier
     * TYPE: String (uppercase)
     * REQUIRED: Yes
     * UNIQUE: Yes - prevents duplicate product codes
     * 
     * EXAMPLE: SKU-001, PROD-ABC-123, etc.
     * 
     * WHY: Used to quickly identify products without relying on database IDs
     * Humans can read SKUs easier than MongoDB ObjectIds
     */
    sku: {
        type: String,
        required: [true, 'Please provide SKU'],
        unique: true,
        uppercase: true,
        trim: true,
    },
    /**
     * NAME FIELD
     * 
     * WHAT: Product's display name
     * TYPE: String
     * REQUIRED: Yes
     * 
     * EXAMPLE: "Samsung 65-inch 4K TV", "Apple AirPods Pro"
     */
    name: {
        type: String,
        required: [true, 'Please provide product name'],
        trim: true,
    },
    /**
     * DESCRIPTION FIELD
     * 
     * WHAT: Product details and features
     * TYPE: String
     * REQUIRED: No (can be generated by AI on Day 7)
     * DEFAULT: Empty string
     * 
     * NOTE: On Day 7-8, AI will auto-generate descriptions
     * This field will store AI-generated or manual descriptions
     * 
     * EXAMPLE: "High-quality 65-inch 4K Smart TV with Dolby Vision..."
     */
    description: {
        type: String,
        default: '',
        trim: true,     
    },
    /**
     * CATEGORY FIELD
     * 
     * WHAT: Product category for organization
     * TYPE: String (enum - fixed options)
     * ENUM: Limited to predefined categories
     * DEFAULT: 'Others'
     * 
     * WHY ENUM: Prevents typos, ensures consistency
     * EXAMPLE: Electronics, Clothing, Food, Home, Other
     * 
     * Can be expanded: ['Electronics', 'Clothing', 'Food', 'Home', 'Others']
     */
    category: {
        type: String,
        enum: ['Electronics', 'Clothing', 'Food', 'Home', 'Others'],
        default: 'Others',
        trim: true,
    },
    /**
     * PRICE FIELD
     * 
     * WHAT: Product's selling price
     * TYPE: Number (currency in dollars/pesos/etc)
     * REQUIRED: Yes
     * MIN: 0 (cannot be negative)
     * 
     * HOW IT'S USED:
     * - Used in sales calculations
     * - Displayed to customers/employees
     * - Can be updated but doesn't affect past sales
     * 
     * IMPORTANT: Price at time of sale is stored in Sale document
     * This ensures we track what customer actually paid
     */
    price: {
        type: Number,
        required: [true, 'Please provide a price'],
        min: [0, 'Price cannot be negative'],
    },
    /**
     * COST FIELD
     * 
     * WHAT: Product's acquisition/wholesale cost
     * TYPE: Number
     * REQUIRED: Yes
     * MIN: 0
     * 
     * HOW IT'S USED:
     * - Calculate profit margins
     * - Used in Day 6 analytics (profit reports)
     * - profit = price - cost
     * 
     * EXAMPLE: If cost=50 and price=100, profit per unit=50
     */
    cost: {
        type: Number,
        required: [true, 'Please provide a cost'],
        min: [0, 'Cost cannot be negative'],
    },
    /**
     * STOCK FIELD
     * 
     * WHAT: Current quantity in inventory
     * TYPE: Number
     * REQUIRED: Yes
     * MIN: 0
     * DEFAULT: 0
     * 
     * HOW IT'S UPDATED:
     * - Increases: When new stock arrives (admin adds)
     * - Decreases: When sold (Day 4 sales logic decrements automatically)
     * 
     * EXAMPLE: If stock=100 and we sell 5 units, stock becomes 95
     */
    stock: {
        type: Number,
        required: [true, 'Please provide stock quantity'],
        min: [0, 'Stock cannot be negative'],
        default: 0,
    },
    /**
     * MIN STOCK FIELD
     * 
     * WHAT: Minimum stock level before reordering
     * TYPE: Number
     * DEFAULT: 10
     * 
     * HOW IT'S USED:
     * - Day 6 Analytics: alerts when stock falls below this
     * - Purchasing: signals when to order more inventory
     * - Day 7-8 AI: suggests discounts for products below minStock
     * 
     * EXAMPLE: If minStock=10 and stock=8, product needs reorder
     */
    minStock: {
        type: Number,
        default: 10,
        min: [0, 'Minimum stock cannot be negative']
    },
    /**
     * SUPPLIER FIELD
     * 
     * WHAT: Name of the supplier/vendor
     * TYPE: String
     * REQUIRED: No
     * DEFAULT: Empty string
     * 
     * HOW IT'S USED:
     * - Track where product came from
     * - Contact for reorders
     * - Day 6 Analytics: supplier performance
     * 
     * EXAMPLE: "Samsung", "Nike Distributor", "Local Vendor"
     */
    supplier: {
        type: String,
        default: '',
        trim: true,
    },
    /**
     * AI GENERATED FLAG
     * 
     * WHAT: Boolean indicating if description was AI-generated
     * TYPE: Boolean
     * DEFAULT: false
     * 
     * HOW IT'S USED:
     * - Day 7-8: When AI generates description, set to true
     * - Frontend: Can show badge "AI-Generated" to user
     * - Tracking: Know which descriptions are from AI vs manual
     * 
     * EXAMPLE: 
     * Admin clicks "Generate Description" with AI
     * → Backend calls Google Gemini
     * → Description filled in, aiGenerated = true
     */
    aiGenerated: {
        type: Boolean,
        default: false,
    },
    /**
     * TIMESTAMPS
     * 
     * AUTOMATICALLY MANAGED BY MONGOOSE:
     * - createdAt: Set when product created
     * - updatedAt: Updated whenever product is modified
     * 
     * USED FOR:
     * - Day 6 Analytics: Track when products added
     * - Sorting: Show newest products first
     * - Auditing: See product history
     */  
}, { timeStamp: true }
);

/**
 * INDEX FOR SEARCH PERFORMANCE
 * 
 * Mongoose automatically indexes unique fields (SKU)
 * But we can add more indexes for frequently searched fields
 * 
 * This helps MongoDB find products by name quickly
 */
productSchema.index({ name: 'text', description: 'text' });

module.exports = mongoose.model('Product', productSchema);